server:
  port: 8083
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:product-service
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console