server:
  port: 8083
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:product-service
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true